/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeputadosIndexRouteImport } from './routes/deputados.index'
import { Route as ProposicoesIndexRouteImport } from './routes/proposicoes.index'
import { Route as VotacoesIndexRouteImport } from './routes/votacoes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeputadosIndexRoute = DeputadosIndexRouteImport.update({
  id: '/deputados/',
  path: '/deputados/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposicoesIndexRoute = ProposicoesIndexRouteImport.update({
  id: '/proposicoes/',
  path: '/proposicoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotacoesIndexRoute = VotacoesIndexRouteImport.update({
  id: '/votacoes/',
  path: '/votacoes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deputados/': typeof DeputadosIndexRoute
  '/proposicoes/': typeof ProposicoesIndexRoute
  '/votacoes/': typeof VotacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deputados': typeof DeputadosIndexRoute
  '/proposicoes': typeof ProposicoesIndexRoute
  '/votacoes': typeof VotacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deputados/': typeof DeputadosIndexRoute
  '/proposicoes/': typeof ProposicoesIndexRoute
  '/votacoes/': typeof VotacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deputados/' | '/proposicoes/' | '/votacoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deputados' | '/proposicoes' | '/votacoes'
  id: '__root__' | '/' | '/deputados/' | '/proposicoes/' | '/votacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeputadosIndexRoute: typeof DeputadosIndexRoute
  ProposicoesIndexRoute: typeof ProposicoesIndexRoute
  VotacoesIndexRoute: typeof VotacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deputados/': {
      id: '/deputados/'
      path: '/deputados'
      fullPath: '/deputados/'
      preLoaderRoute: typeof DeputadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposicoes/': {
      id: '/proposicoes/'
      path: '/proposicoes'
      fullPath: '/proposicoes/'
      preLoaderRoute: typeof ProposicoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votacoes/': {
      id: '/votacoes/'
      path: '/votacoes'
      fullPath: '/votacoes/'
      preLoaderRoute: typeof VotacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeputadosIndexRoute: DeputadosIndexRoute,
  ProposicoesIndexRoute: ProposicoesIndexRoute,
  VotacoesIndexRoute: VotacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
